[project]
name = "langgraph-agent-lightning-optimization"
version = "0.1.0"
description = "LangGraph agent optimization using Agent Lightning's framework with APO algorithm. Room booking assistant example with Langsmith tracing"
authors = [{name="Simon Budziak", company="Soba Labs"}]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agentlightning>=0.3.0",
    "langchain-openai>=1.1.7",
    "langgraph>=1.0.7",
    "poml>=0.0.8",
]

[dependency-groups]
dev = [
    "ruff>=0.14.14",
]
